// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_RsDbfV9oImU1VgPQyDZ06yzdHkKXS8',
    appId: '1:821740868414:android:9ef92589d53065f8ee526f',
    messagingSenderId: '821740868414',
    projectId: 'service-sphere-swifttech',
    storageBucket: 'service-sphere-swifttech.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bQR6Eij7tw_gWGaXIjO1CPL2-nxczyc',
    appId: '1:821740868414:ios:ca346b728c98b910ee526f',
    messagingSenderId: '821740868414',
    projectId: 'service-sphere-swifttech',
    storageBucket: 'service-sphere-swifttech.firebasestorage.app',
    androidClientId: '821740868414-vb1471pe473td8i30084m2g0s1u4bpos.apps.googleusercontent.com',
    iosClientId: '821740868414-de4u50mihp14lh6n70v3662vlhot24vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHomeServiceProviderAppClone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDej4_rYbWzRovhdiTnl4-xVIqJvSHBww8',
    appId: '1:821740868414:web:bbb05818c096980eee526f',
    messagingSenderId: '821740868414',
    projectId: 'service-sphere-swifttech',
    authDomain: 'service-sphere-swifttech.firebaseapp.com',
    storageBucket: 'service-sphere-swifttech.firebasestorage.app',
    measurementId: 'G-DRPNCSPFJ1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bQR6Eij7tw_gWGaXIjO1CPL2-nxczyc',
    appId: '1:821740868414:ios:ca346b728c98b910ee526f',
    messagingSenderId: '821740868414',
    projectId: 'service-sphere-swifttech',
    storageBucket: 'service-sphere-swifttech.firebasestorage.app',
    androidClientId: '821740868414-vb1471pe473td8i30084m2g0s1u4bpos.apps.googleusercontent.com',
    iosClientId: '821740868414-de4u50mihp14lh6n70v3662vlhot24vq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHomeServiceProviderAppClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDej4_rYbWzRovhdiTnl4-xVIqJvSHBww8',
    appId: '1:821740868414:web:584e917ea9bfe592ee526f',
    messagingSenderId: '821740868414',
    projectId: 'service-sphere-swifttech',
    authDomain: 'service-sphere-swifttech.firebaseapp.com',
    storageBucket: 'service-sphere-swifttech.firebasestorage.app',
    measurementId: 'G-BC8TQJYNMN',
  );

}